language: c

jobs:
  include:
    -
      os: linux
      dist: jammy
    -
      os: linux
      dist: focal
    -
      os: linux
      dist: bionic

before_install:
  - sudo apt -y update
  - sudo apt -y upgrade
  - sudo apt dist-upgrade
  - apt-cache search linux-headers-.*-generic
  - sudo apt -y install linux-headers-$(uname -r) dkms git bc
script: make
